version: "3"

services:
  validator-node:
    image: $QCLIENT_IMAGE
    entrypoint: ["geth", "--datadir=/data", "--nat=extip:$IP", "--port=$EXT_PORT", "--unlock=$ADDRESS",  "--password=/data/keystore/pwd.txt", "--miner.etherbase=$ADDRESS", "--mine", "--miner.threads=1", "--syncmode=full", "--rpc.allow-unprotected-txs", "--verbosity=3", "--miner.gasprice=1"]
    volumes:
      - ./keystore:/data/keystore
      - ./additional:/data/additional
      - validator-node-data:/data
    ports:
    - $EXT_PORT:$EXT_PORT/tcp
    - $EXT_PORT:$EXT_PORT/udp
    restart: unless-stopped

volumes:
  validator-node-data:

