version: "3"

services:
  rootnode:
    image: $QCLIENT_IMAGE
    entrypoint: ["geth", "--datadir=/data", "--nat=extip:$IP", "--port=$EXT_PORT", "--unlock=$ADDRESS", "--password=/data/keystore/pwd.txt", "--miner.etherbase=$ADDRESS",  "--syncmode=full", "--verbosity=3"]
    volumes:
      - ./keystore:/data/keystore
      - ./additional:/data/additional
      - rootnode-data:/data
    ports:
    - $EXT_PORT:$EXT_PORT/tcp
    - $EXT_PORT:$EXT_PORT/udp
    restart: unless-stopped

volumes:
  rootnode-data:

