version: "3"

services:
  fullnode:
    image: qblockchain/q-client:mainnet
    entrypoint: ["geth", "--datadir=/data", "--http", "--http.corsdomain=*", "--http.addr=0.0.0.0", "--syncmode=full", "--rpc.allow-unprotected-txs", "--verbosity=3", "--miner.gasprice=50000000000", "--txpool.pricelimit=47619047619", "--http.api=net,web3,eth,debug"]
    volumes:
      - fullnode-data:/data
    ports:
    - $EXT_PORT:8545
    restart: unless-stopped

  local-explorer:
    image: alethio/ethereum-lite-explorer
    depends_on:
      - node
    environment:
      - APP_NODE_URL=http://localhost:$EXT_PORT
    ports:
      - $EXPLORER_PORT:80
    restart: unless-stopped

volumes:
  fullnode-data:
