version: "3"

services:
  fullnode:
    image: $QCLIENT_IMAGE
    entrypoint: [
      "geth",
      "--datadir=/data",
      "--syncmode=full",
      "--bootnodes=$BOOTNODE1_ADDR,$BOOTNODE2_ADDR,$BOOTNODE3_ADDR",
      "--verbosity=3",
      "--port=$EXT_PORT",
      "--http",
      "--http.corsdomain=*",
      "--http.addr=0.0.0.0",
      "--http.api=net,web3,eth"
    ]
    volumes:
      - fullnode-data:/data
    ports:
      - $EXT_PORT:$EXT_PORT
      - $EXT_PORT:$EXT_PORT/udp
      - 8545:8545
      - 8546:8546
    restart: unless-stopped

  local-explorer:
    image: alethio/ethereum-lite-explorer
    depends_on:
      - fullnode
    environment:
      - APP_NODE_URL=http://localhost:$EXT_PORT
    ports:
      - $EXPLORER_PORT:80
    restart: unless-stopped

volumes:
  fullnode-data:
